version: 2.1
orbs:
  scan: prisma_cloud/devops_security@1.0.0
jobs:
  scan_iac: scan/prisma_cloud
  docker_build_and_save:
    executor: scan/compute
    steps:
      - checkout
      - run: docker pull nginx
      - run: mkdir -p workspace
      - run: docker image
      - run: 'docker save nginx:latest -o workspace/image.tar'
      - persist_to_workspace:
          root: workspace
          paths:
            - image.tar
workflows:
  scan:
    jobs:
      - scan_iac:
          prisma_cloud_api_url: https://api3.prismacloud.io
          access_key: 962c246c-7c24-4eb6-9271-f153a26fc7ee
          secret_key: nf4fiputYUBioq6KFqZPyBS+RG8=
          templates_directory_path: awsdemo
          failure_criteria_high_severity: 1
          failure_criteria_medium_severity: 1
          failure_criteria_low_severity: 1
          failure_criteria_operator: or
      - docker_build_and_save
      - scan/scan_image:
          requires:
            - docker_build_and_save
          prisma_cloud_compute_url: https://us-east1.cloud.twistlock.com/us-1-111573360
          prisma_cloud_compute_user: 962c246c-7c24-4eb6-9271-f153a26fc7ee
          prisma_cloud_compute_pass: PC_COMPUTE_PASS
          image: nginx:latest
          image_tar: image.tar
          vulnerability_threshold: critical
          compliance_threshold: ''
          only_fixed: true
